parameters:

services:
    pouzor_lol_stat.mashape_api:
        class: Pouzor\Bundle\LolStatBundle\Services\MashapeAPIService
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        public: false	

    pouzor_lol_stat.twig.League_extension:
        class: Pouzor\Bundle\LolStatBundle\Twig\LeagueExtension
        tags:
            - { name: twig.extension }