<?php

namespace Pouzor\Bundle\LolStatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionRepository extends EntityRepository
{
    public function findAllOrdered() {
        $qBuilder = $this->getEntityManager()
            ->createQueryBuilder()
            ->from("PouzorLolStatBundle:Champion", "c")
            ->select('c')
            ->orderBy("c.name", "ASC");


        return $qBuilder->getQuery()->getArrayResult();
    }
}
